- hosts: webservers
  vars:
    - jenkins_workspace: ""

  remote_user: ec2_user
  tasks:
  - name: copy archive file from local to remote
    copy:
      src: /
      dest: /home/ec2-user
      owner: ec2_user

  - name: write the apache config file
    template:
      src: /srv/httpd.j2
      dest: /etc/httpd.conf
    notify:
    - restart apache
  - name: ensure apache is running
    service:
      name: httpd
      state: started
  handlers:
    - name: restart apache
      service:
        name: httpd
        state: restarted