# file: production

[webservers]
13.232.102.99 ansible_ssh_user=ec2-user ansible_ssh_private_key_file=/var/jenkins_home/ansible/Mumbai-admin.pem

[middleware]
ec2-13-233-15-65.ap-south-1.compute.amazonaws.com ansible_ssh_user=ec2_user
