# file: production

[webservers]
10.0.0.16 ansible_ssh_user=ec2_user ansible_ssh_private_key_file=/var/jenkins_home/ansible/Mumbai-admin.pem

[middleware]
ec2-13-233-15-65.ap-south-1.compute.amazonaws.com ansible_ssh_user=ec2_user
